#!/bin/bash



while true
 do
    read -p "Enter Name of Table: " table
    
    if [ -f "$table" ]
     then
        echo "Table already exists."
    else
        touch "$table.table"
	touch "Meta_$table"
        echo "Table Created"
	
	read -p "Enter Number of column: " n
	
	read -p "Enter Name of Primary Column: " c
	echo "$c" >> "Meta_$table"
	
	#echo $n
	sed -i 's/$/\np/' "./Meta_$table"
	for ((i=2; i<="$n"; i++))
        do
		read -p "Name of Column $i: " c
		read -p "Integer(i) or String(s): " s
	    	
		sed -i "1s/$/:$c/" "Meta_$table"
		sed -i "2s/$/:$s/" "Meta_$table"
		

        done
	
    fi

    read -p "Do you want to create another Table? (1) Yes / (2) No: " choice
    
    if [ "$choice" != "1" ]
     then
     	optionstable
        break
    fi
done
