#! /usr/bin/bash

export DBName
if [[ ! "$PWD" =~ ${Database}$ ]]
 then
    cd $Database/
fi
pwd
export DBName
read -p "Please Enter exists Datbase: " DBName
if [ ! -d "$DBName" ]
then
	echo "Not Exists"
	echo "Do you Want to Back or Quit"
	pwd

	select option in Back Quit
	do
	case $REPLY in
	1)
	cd ../
	./DB
	break;
	;;
	2)
	break;
	;;
	esac
	done
	
else

optionstable
	
fi
