#! /usr/bin/bash


#cd ./DBMS

if [[ ! "pwd" =~ ${HOME/DBMS}$ ]]
 then

    cd $HOME/DBMS
fi
export Database="./Database"

if [ ! -d $Database ]
then
	mkdir $Database
	cd $Database
fi
pwd
select option in ConnectDatabase CreateDatabase ListDatabase DropDatabase Quit
do

case $REPLY in
1)
DBConnect
break;
;;

2)
./DBCreate
;;

3)
./DBList
;;

4)
./DBDrop
;;

5)
break;

;;
esac

done
