#! /usr/bin/bash

# Set the Database directory path as an absolute path


cd $DBName

#echo "Checking the existence of the specified Database..."

#read -p "Please Enter the Database: " DBName

read -p "Please Enter the Table to drop: " TBName

if [ -f "$TBName" ]
    then
        echo "Found table directory: $Database/$DBName/$TBName"
        echo "Dropping the table '$TBName' and its columns..."
        rm "$TBName"

        if [ $? -eq 0 ]
        then
            echo "The table '$TBName' has been successfully dropped."
        else
            echo "An error occurred while dropping the table '$TBName'."
        fi
    else
        echo "The table '$TBName' does not exist."
        echo "Do you want to Go Back or Quit?"
    fi
