#! /usr/bin/bash

pwd
read -p "Please Enter the Table to insert into: " TBName
if [ ! -f "$TBName" ]
then
    echo "The Table '$TBName' does not exist."
    echo "Do you Want to Go Back or Quit?"
    exit 1
fi

echo "Inserting data into '$TBName'."

while true
do
	echo "Enter data in the format "
    awk -F: '
{
	i=1
	if(NR==1)
	{
	print $0
	}
}' "./Meta_$TBName"

    read -p "(or 'quit' to exit): " inputData

    if [ "$inputData" == "quit" ]
    then
        echo "Quitting..."
        exit 0
    fi

    # Append the input data to the table file
    echo "$inputData" >> "$TBName"

    if [ $? -eq 0 ]
    then
        echo "Data has been successfully inserted into '$TBName'."
    else
        echo "An error occurred while inserting data into '$TBName'."
    fi
done


