#! /usr/bin/bash


cd $DBName


if [ -f >= 0 ]
then
	find -type f
else
	echo "Nothing to Show"
	read -p "Enter 1 to Back: " b

	if [ $b == 1 ]
	then 
		../../optionstable
	else 
		echo "Error Rerun DB"
	fi
	
fi
