#! /usr/bin/bash


if [[ "$(find -type f | grep ".table" | wc -l)" -gt 0 ]]
then
	find -type f | grep ".table"
	read -p "Enter 1 to Back: " b

	if [ $b == 1 ]
	then 
		#cd ~
		optionstable
		
	else 
		echo "Error Rerun DB"
	fi
	
else
	echo "Nothing to Show"
	read -p "Enter 1 to Back: " b

	if [ $b == 1 ]
	then 
		#cd ~
		optionstable
		
	else 
		echo "Error Rerun DB"
	fi
	
fi
