#! /usr/bin/bash


if [[ ! "$PWD" =~ ${DBName}$ ]]
 then
    cd $DBName/
fi

pwd
select option in CreateTable ListTables DropTable InsertintoTable SelectfromTable DeletefromTable UpdateTable Back
do

case $REPLY in
1)
CreateTable
break;
;;

2)

ListTables

break;
;;

3)
DropTable
break;
;;

4)
InsertintoTable
break;
;;

5)
SelectfromTable
break;
;;
6)
DeletefromTable
break;
;;

7)
UpdateTable
break;
;;

8)
DB
break;
;;
esac

done
