#! /usr/bin/bash


select option in CreateTable ListTables DropTable InsertintoTable SelectfromTable DeletefromTable UpdateTable
do

case $REPLY in
1)
../CreateTable
;;

2)
../ListTables
;;

3)
../DropTable
;;

4)
../InsertintoTable
;;

5)
../SelectfromTable
;;
6)
../DeletefromTable
;;

7)
../UpdateTable
;;

8)
break;
;;
esac

done
